name: Mekanik APK Yapici

on:
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Python Kurulumu
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Flutter Ortami Kurulumu
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.2'

      - name: Gereklilikleri Yukle
        run: pip install packaging

      - name: Flet 0.25.2 Zorla Kur ve APK Yap (LOGOLU)
        run: |
          pip uninstall -y flet
          pip install flet==0.25.2
          flet --version
          yes | flet build apk --verbose --icon logo.png --product "Harcama Takibi"

      - name: APK Dosyasini Paketle ve Sun
        uses: actions/upload-artifact@v4
        with:
          name: MekanikButce-APK
          path: build/apk/app-release.apk
