name: Mekanik APK Yapici

on:
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Python Kurulumu
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Flutter Ortami Kurulumu (Modern Surum)
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.2'

      - name: Flet Kutuphanesini Yukle
        run: pip install -r requirements.txt

      - name: APK Ä°nsa Et (Full Paket)
        run: yes | flet build apk --verbose --icon logo.png --product "Harcama Takibi"

      - name: APK Dosyasini Paketle ve Sun
        uses: actions/upload-artifact@v4
        with:
          name: MekanikButce-APK
          path: build/apk/app-release.apk
