name: Mekanik APK Yapici

on:
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Python Kurulumu
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Flutter Ortami Kurulumu
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.2'

      - name: Flet Kutuphanesini Yukle
        # requirements.txt icindeki google-generativeai kütüphanesini de yükleyecek
        run: pip install -r requirements.txt

      - name: APK İnsa Et (Otomatik Isim)
        # Repo adi neyse uygulama adi o olacak
        run: yes | flet build apk --verbose

      - name: APK Dosyasini Paketle ve Sun
        uses: actions/upload-artifact@v4
        with:
          name: HarcamaTakibi-APK
          path: build/apk/app-release.apk
